In [30]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np
import pandas as pd
import math
from dtw import *
from scipy.spatial.distance import euclidean, pdist

matplotlib.use('Qt5Agg')

DATA_PATH = "C:\\Users\\gaoch\\MA\\Badminton weights\\P01_B\\"

SHEET_NAME = ["Segment Position", "Segment Velocity", "Segment Acceleration"]

SIMPLIFIED_JOINTS = ["Head", "Neck", "Left Upper Arm", "Right Upper Arm", "Left Forearm", "Right Forearm",
                     "Left Hand", "Right Hand", "Pelvis", "Left Upper Leg", "Right Upper Leg",
                     "Left Lower Leg", "Right Lower Leg", "Left Foot", "Right Foot"]

SKELETON_CONNECTION_MAP = [["Neck", "Head"],
                           ["Neck", "Left Upper Arm"],
                           ["Left Upper Arm", "Left Forearm"],
                           ["Left Forearm", "Left Hand"],
                           ["Neck", "Right Upper Arm"],
                           ["Right Upper Arm", "Right Forearm"],
                           ["Right Forearm", "Right Hand"],
                           ["Neck", "Pelvis"],
                           ["Pelvis", "Left Upper Leg"],
                           ["Left Upper Leg", "Left Lower Leg"],
                           ["Left Lower Leg", "Left Foot"],
                           ["Pelvis", "Right Upper Leg"],
                           ["Right Upper Leg", "Right Lower Leg"],
                           ["Right Lower Leg", "Right Foot"]]

used_cols = []
for joints in SIMPLIFIED_JOINTS:
    used_cols.append(joints + " x")
    used_cols.append(joints + " y")
    used_cols.append(joints + " z")

DATA_PATH = "C:\\Users\\gaoch\\MA\\Badminton weights\\P01_B\\head10000\\"

SHEET_NAME = ["Segment Position", "Segment Velocity", "Segment Acceleration"]

# motion_recording = pd.read_excel(DATA_PATH + "P01_B_noweightwithgloves.xlsx",
#                          sheet_name = SHEET_NAME,
#                          usecols = used_cols)

position_recording_0 = pd.read_csv(DATA_PATH + "position.csv")[2650:2800]
velocity_recording_0 = pd.read_csv(DATA_PATH + "velocity.csv")[2650:2800]
position_recording_1 = pd.read_csv(DATA_PATH + "position.csv")[2600:2750]


def frame_distance(frame_0, frame_1):
    distances = []
    for index in range(0, len(frame_0), 3):
        joint_in_frame_0 = [frame_0[index], frame_0[index + 1], frame_0[index + 2]]
        joint_in_frame_1 = [frame_1[index], frame_1[index + 1], frame_1[index + 2]]
        distances.append(euclidean(joint_in_frame_0, joint_in_frame_1))
    distances.append(sum(distances))
    return distances

a = position_recording_0.iloc[:, :3].values - position_recording_1.iloc[:, :3].values
d = np.square(a)
print(a)

[[ 8.28295450e-02  2.51926900e-02 -2.21597730e-03]
 [ 8.41286582e-02  2.53419427e-02 -3.12226370e-03]
 [ 8.54503748e-02  2.54934683e-02 -4.05107500e-03]
 [ 8.67866472e-02  2.56651222e-02 -4.99759043e-03]
 [ 8.81294275e-02  2.58747601e-02 -5.95698923e-03]
 [ 8.94706680e-02  2.61402377e-02 -6.92445064e-03]
 [ 9.08023209e-02  2.64794104e-02 -7.89515391e-03]
 [ 9.21294998e-02  2.69037425e-02 -8.86943907e-03]
 [ 9.34576824e-02  2.74112655e-02 -9.84671481e-03]
 [ 9.47792441e-02  2.79870520e-02 -1.08354779e-02]
 [ 9.60931604e-02  2.86105537e-02 -1.18449412e-02]
 [ 9.74018308e-02  2.92710462e-02 -1.28699608e-02]
 [ 9.87076546e-02  2.99578053e-02 -1.39053927e-02]
 [ 1.00013031e-01  3.06601067e-02 -1.49460932e-02]
 [ 1.01320360e-01  3.13672260e-02 -1.59869184e-02]
 [ 1.02632041e-01  3.20684391e-02 -1.70227245e-02]
 [ 1.03950472e-01  3.27530214e-02 -1.80483675e-02]
 [ 1.05278054e-01  3.34102489e-02 -1.90587036e-02]
 [ 1.06617185e-01  3.40293972e-02 -2.00485890e-02]
 [ 1.07989023e-01  3.46230030e-

In [22]:
X = [[1,2],[2,3],[3,4],[3,4]];
D = pdist(X)
print(D)

[1.41421356 2.82842712 2.82842712 1.41421356 1.41421356 0.        ]
